name: Build fastPathSign

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout TrollStore repository
        uses: actions/checkout@v4

      - name: Fetch ChOma src files only
        run: |
          mkdir -p ./Exploits/fastPathSign/src
          git clone --depth=1 --filter=blob:none --sparse https://github.com/opa334/ChOma.git tmp_choma
          cd tmp_choma
          git sparse-checkout set src
          cp -R src/* ../Exploits/fastPathSign/src/
          cd ..
          rm -rf tmp_choma

      - name: Install dependencies
        run: |
          brew install ldid pkg-config

      - name: Build fastPathSign
        working-directory: ./Exploits/fastPathSign
        run: |
          make clean
          make
          ls -la

      - name: Upload fastPathSign binary
        uses: actions/upload-artifact@v4
        with:
          name: fastPathSign-binary
          path: ./Exploits/fastPathSign/fastPathSign
